// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AchievementUsecase is an autogenerated mock type for the AchievementUsecase type
type AchievementUsecase struct {
	mock.Mock
}

// GetAchievementsByTarget provides a mock function with given fields: ctx, targetID
func (_m *AchievementUsecase) GetAchievementsByTarget(ctx context.Context, targetID string) ([]*domain.Achievement, error) {
	ret := _m.Called(ctx, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetAchievementsByTarget")
	}

	var r0 []*domain.Achievement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Achievement, error)); ok {
		return rf(ctx, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Achievement); ok {
		r0 = rf(ctx, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Achievement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordAchievement provides a mock function with given fields: ctx, input
func (_m *AchievementUsecase) RecordAchievement(ctx context.Context, input domain.RecordAchievementInput) (*domain.Achievement, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordAchievement")
	}

	var r0 *domain.Achievement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RecordAchievementInput) (*domain.Achievement, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RecordAchievementInput) *domain.Achievement); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Achievement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RecordAchievementInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAchievementUsecase creates a new instance of AchievementUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAchievementUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AchievementUsecase {
	mock := &AchievementUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
