// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AchievementRepository is an autogenerated mock type for the AchievementRepository type
type AchievementRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, achievement
func (_m *AchievementRepository) Create(ctx context.Context, achievement *domain.Achievement) error {
	ret := _m.Called(ctx, achievement)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Achievement) error); ok {
		r0 = rf(ctx, achievement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTargetID provides a mock function with given fields: ctx, targetID
func (_m *AchievementRepository) GetByTargetID(ctx context.Context, targetID string) ([]*domain.Achievement, error) {
	ret := _m.Called(ctx, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTargetID")
	}

	var r0 []*domain.Achievement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Achievement, error)); ok {
		return rf(ctx, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Achievement); ok {
		r0 = rf(ctx, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Achievement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAchievementRepository creates a new instance of AchievementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAchievementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AchievementRepository {
	mock := &AchievementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
