// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EmployeeUsecase is an autogenerated mock type for the EmployeeUsecase type
type EmployeeUsecase struct {
	mock.Mock
}

// GetAllEmployees provides a mock function with given fields: ctx
func (_m *EmployeeUsecase) GetAllEmployees(ctx context.Context) ([]*domain.Employee, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllEmployees")
	}

	var r0 []*domain.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Employee, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Employee); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployeeDetails provides a mock function with given fields: ctx, id
func (_m *EmployeeUsecase) GetEmployeeDetails(ctx context.Context, id string) (*domain.Employee, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployeeDetails")
	}

	var r0 *domain.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Employee, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Employee); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterEmployee provides a mock function with given fields: ctx, input
func (_m *EmployeeUsecase) RegisterEmployee(ctx context.Context, input domain.CreateEmployeeInput) (*domain.Employee, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RegisterEmployee")
	}

	var r0 *domain.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateEmployeeInput) (*domain.Employee, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateEmployeeInput) *domain.Employee); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateEmployeeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEmployee provides a mock function with given fields: ctx, input
func (_m *EmployeeUsecase) UpdateEmployee(ctx context.Context, input domain.UpdateEmployeeInput) (*domain.Employee, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmployee")
	}

	var r0 *domain.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateEmployeeInput) (*domain.Employee, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateEmployeeInput) *domain.Employee); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateEmployeeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEmployeeUsecase creates a new instance of EmployeeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeUsecase {
	mock := &EmployeeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
