// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MeetingMinuteUsecase is an autogenerated mock type for the MeetingMinuteUsecase type
type MeetingMinuteUsecase struct {
	mock.Mock
}

// CreateMeeting provides a mock function with given fields: ctx, input
func (_m *MeetingMinuteUsecase) CreateMeeting(ctx context.Context, input domain.CreateMeetingInput) (*domain.MeetingMinute, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateMeeting")
	}

	var r0 *domain.MeetingMinute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateMeetingInput) (*domain.MeetingMinute, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateMeetingInput) *domain.MeetingMinute); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MeetingMinute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateMeetingInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteMeeting provides a mock function with given fields: ctx, id
func (_m *MeetingMinuteUsecase) DeleteMeeting(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMeeting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllMeetings provides a mock function with given fields: ctx
func (_m *MeetingMinuteUsecase) GetAllMeetings(ctx context.Context) ([]*domain.MeetingMinute, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMeetings")
	}

	var r0 []*domain.MeetingMinute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.MeetingMinute, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.MeetingMinute); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MeetingMinute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMeetingDetails provides a mock function with given fields: ctx, id
func (_m *MeetingMinuteUsecase) GetMeetingDetails(ctx context.Context, id string) (*domain.MeetingMinute, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMeetingDetails")
	}

	var r0 *domain.MeetingMinute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MeetingMinute, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MeetingMinute); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MeetingMinute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMeeting provides a mock function with given fields: ctx, input
func (_m *MeetingMinuteUsecase) UpdateMeeting(ctx context.Context, input domain.UpdateMeetingInput) (*domain.MeetingMinute, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMeeting")
	}

	var r0 *domain.MeetingMinute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateMeetingInput) (*domain.MeetingMinute, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateMeetingInput) *domain.MeetingMinute); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MeetingMinute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateMeetingInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskStatus provides a mock function with given fields: ctx, input
func (_m *MeetingMinuteUsecase) UpdateTaskStatus(ctx context.Context, input domain.UpdateResultStatusInput) (*domain.MeetingResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskStatus")
	}

	var r0 *domain.MeetingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateResultStatusInput) (*domain.MeetingResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateResultStatusInput) *domain.MeetingResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MeetingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateResultStatusInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMeetingMinuteUsecase creates a new instance of MeetingMinuteUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeetingMinuteUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeetingMinuteUsecase {
	mock := &MeetingMinuteUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
