// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MeetingMinuteRepository is an autogenerated mock type for the MeetingMinuteRepository type
type MeetingMinuteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, meeting
func (_m *MeetingMinuteRepository) Create(ctx context.Context, meeting *domain.MeetingMinute) error {
	ret := _m.Called(ctx, meeting)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MeetingMinute) error); ok {
		r0 = rf(ctx, meeting)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MeetingMinuteRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *MeetingMinuteRepository) GetAll(ctx context.Context) ([]*domain.MeetingMinute, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.MeetingMinute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.MeetingMinute, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.MeetingMinute); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MeetingMinute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MeetingMinuteRepository) GetByID(ctx context.Context, id string) (*domain.MeetingMinute, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.MeetingMinute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MeetingMinute, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MeetingMinute); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MeetingMinute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultByID provides a mock function with given fields: ctx, resultID
func (_m *MeetingMinuteRepository) GetResultByID(ctx context.Context, resultID string) (*domain.MeetingResult, error) {
	ret := _m.Called(ctx, resultID)

	if len(ret) == 0 {
		panic("no return value specified for GetResultByID")
	}

	var r0 *domain.MeetingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.MeetingResult, error)); ok {
		return rf(ctx, resultID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.MeetingResult); ok {
		r0 = rf(ctx, resultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MeetingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, meeting
func (_m *MeetingMinuteRepository) Update(ctx context.Context, meeting *domain.MeetingMinute) error {
	ret := _m.Called(ctx, meeting)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MeetingMinute) error); ok {
		r0 = rf(ctx, meeting)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateResult provides a mock function with given fields: ctx, result
func (_m *MeetingMinuteRepository) UpdateResult(ctx context.Context, result *domain.MeetingResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MeetingResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMeetingMinuteRepository creates a new instance of MeetingMinuteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeetingMinuteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeetingMinuteRepository {
	mock := &MeetingMinuteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
