// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TargetRepository is an autogenerated mock type for the TargetRepository type
type TargetRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, target
func (_m *TargetRepository) Create(ctx context.Context, target *domain.Target) error {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Target) error); ok {
		r0 = rf(ctx, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TargetRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEmployeeAndPeriod provides a mock function with given fields: ctx, employeeID, month, year
func (_m *TargetRepository) GetByEmployeeAndPeriod(ctx context.Context, employeeID string, month int, year int) ([]*domain.Target, error) {
	ret := _m.Called(ctx, employeeID, month, year)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmployeeAndPeriod")
	}

	var r0 []*domain.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Target, error)); ok {
		return rf(ctx, employeeID, month, year)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Target); ok {
		r0 = rf(ctx, employeeID, month, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, employeeID, month, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TargetRepository) GetByID(ctx context.Context, id string) (*domain.Target, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Target, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Target); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, target
func (_m *TargetRepository) Update(ctx context.Context, target *domain.Target) error {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Target) error); ok {
		r0 = rf(ctx, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTargetRepository creates a new instance of TargetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetRepository {
	mock := &TargetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
