// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/faridlan/employee-tracker-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TargetUsecase is an autogenerated mock type for the TargetUsecase type
type TargetUsecase struct {
	mock.Mock
}

// AssignTargetToEmployee provides a mock function with given fields: ctx, input
func (_m *TargetUsecase) AssignTargetToEmployee(ctx context.Context, input domain.AssignTargetInput) (*domain.Target, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AssignTargetToEmployee")
	}

	var r0 *domain.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AssignTargetInput) (*domain.Target, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AssignTargetInput) *domain.Target); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AssignTargetInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateEmployeePerformance provides a mock function with given fields: ctx, employeeID, month, year
func (_m *TargetUsecase) CalculateEmployeePerformance(ctx context.Context, employeeID string, month int, year int) (*domain.EmployeePerformance, error) {
	ret := _m.Called(ctx, employeeID, month, year)

	if len(ret) == 0 {
		panic("no return value specified for CalculateEmployeePerformance")
	}

	var r0 *domain.EmployeePerformance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*domain.EmployeePerformance, error)); ok {
		return rf(ctx, employeeID, month, year)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *domain.EmployeePerformance); ok {
		r0 = rf(ctx, employeeID, month, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EmployeePerformance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, employeeID, month, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTarget provides a mock function with given fields: ctx, id
func (_m *TargetUsecase) DeleteTarget(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTarget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTargetNominal provides a mock function with given fields: ctx, input
func (_m *TargetUsecase) UpdateTargetNominal(ctx context.Context, input domain.UpdateTargetNominalInput) (*domain.Target, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTargetNominal")
	}

	var r0 *domain.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTargetNominalInput) (*domain.Target, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTargetNominalInput) *domain.Target); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateTargetNominalInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTargetUsecase creates a new instance of TargetUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetUsecase {
	mock := &TargetUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
