// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/achievements": {
            "post": {
                "description": "Mencatat riwayat transaksi/pencairan (ledger) baru untuk sebuah target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievement"
                ],
                "summary": "Catat Pencapaian Target",
                "parameters": [
                    {
                        "description": "Payload data pencapaian",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.RecordAchievementRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Pencapaian berhasil dicatat",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_AchievementResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Target tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/categories": {
            "get": {
                "description": "Mengambil daftar semua kategori produk yang tersedia",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "List Semua Kategori",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil daftar kategori",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_CategoryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Menambahkan data kategori produk master ke sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Buat Kategori Baru",
                "parameters": [
                    {
                        "description": "Payload data kategori",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Kategori berhasil dibuat",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/categories/{category_id}/products": {
            "get": {
                "description": "Mengambil daftar produk berdasarkan ID Kategorinya",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "List Produk Berdasarkan Kategori",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kategori",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil produk",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format UUID salah",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/categories/{id}": {
            "get": {
                "description": "Menampilkan detail informasi kategori berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Detail Kategori",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail kategori",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format UUID salah",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Kategori tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Memperbaharui data kategori produk yang ada di dalam sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Update Data Kategori",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload data kategori",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kategori berhasil diperbaharui",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Kategori tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/employees": {
            "get": {
                "description": "Menampilkan semua data karyawan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Data Karyawan",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail karyawan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_EmployeeResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Mendaftarkan data karyawan baru ke dalam sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Registrasi Karyawan Baru",
                "parameters": [
                    {
                        "description": "Payload data karyawan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Karyawan berhasil didaftarkan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_EmployeeResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal menyimpan data karyawan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/employees/{employee_id}/performance": {
            "get": {
                "description": "Melihat total target, total pencapaian, dan persentase performa karyawan pada bulan dan tahun tertentu",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target"
                ],
                "summary": "Kalkulasi Performa Karyawan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Karyawan",
                        "name": "employee_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bulan (1-12)",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Tahun (Misal: 2026)",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menghitung performa",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_PerformanceResponse"
                        }
                    },
                    "400": {
                        "description": "Parameter tidak valid",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Karyawan tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/employees/{id}": {
            "get": {
                "description": "Menampilkan detail informasi karyawan berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Detail Karyawan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Karyawan",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail karyawan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_EmployeeResponse"
                        }
                    },
                    "400": {
                        "description": "Format UUID salah",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Karyawan tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Memperbaharui data karyawan yanga ada di dalam sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Update Karyawan Baru",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Karyawan",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload data karyawan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Karyawan berhasil diperbaharui",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_EmployeeResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Karyawan tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Gagal menyimpan data karyawan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "description": "Mengambil daftar semua produk beserta detail kategorinya",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "List Semua Produk",
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data produk",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Menambahkan data produk baru di bawah kategori tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Buat Produk Baru",
                "parameters": [
                    {
                        "description": "Payload data produk",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Produk berhasil dibuat",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/products/{id}": {
            "get": {
                "description": "Menampilkan detail informasi produk berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Detail Produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Produk",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil detail produk",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format UUID salah",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Produk tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Memperbaharui data produk yang ada di dalam sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Update Data Produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Produk",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload data produk",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Produk berhasil diperbaharui",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Produk tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/targets": {
            "post": {
                "description": "Menetapkan target nominal produk untuk karyawan pada bulan dan tahun tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target"
                ],
                "summary": "Tetapkan Target Karyawan",
                "parameters": [
                    {
                        "description": "Payload penetapan target",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.AssignTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Target berhasil ditetapkan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_TargetDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Karyawan atau Produk tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Target sudah ada (Conflict)",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/targets/{id}": {
            "delete": {
                "description": "Menghapus (Soft Delete) target karyawan berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target"
                ],
                "summary": "Hapus Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Target",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Target berhasil dihapus",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_utils_EmptyObj"
                        }
                    },
                    "400": {
                        "description": "Format UUID salah",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Target tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/targets/{id}/nominal": {
            "patch": {
                "description": "Mengubah hanya nominal dari sebuah target yang sudah ditetapkan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Target"
                ],
                "summary": "Update Nominal Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Target",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload update nominal",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.UpdateTargetNominalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nominal target berhasil diperbaharui",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_TargetDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Format JSON salah atau validasi gagal",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Target tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/targets/{target_id}/achievements": {
            "get": {
                "description": "Mengambil riwayat/ledger pencapaian untuk satu target spesifik",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Achievement"
                ],
                "summary": "List Pencapaian Berdasarkan Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Target",
                        "name": "target_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil riwayat pencapaian",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_AchievementResponse"
                        }
                    },
                    "400": {
                        "description": "Format UUID salah",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Target tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.AchievementResponse": {
            "type": "object",
            "properties": {
                "closing_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nominal": {
                    "type": "integer"
                },
                "target_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.AssignTargetRequest": {
            "type": "object",
            "required": [
                "employee_id",
                "month",
                "nominal",
                "product_id",
                "year"
            ],
            "properties": {
                "employee_id": {
                    "type": "string",
                    "example": "uuid"
                },
                "month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 5
                },
                "nominal": {
                    "type": "integer",
                    "example": 500000000
                },
                "product_id": {
                    "type": "string",
                    "example": "uuid"
                },
                "year": {
                    "type": "integer",
                    "minimum": 2000,
                    "example": 2026
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Kredit Mikro"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_norm": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeRequest": {
            "type": "object",
            "required": [
                "entry_date",
                "name",
                "office_location",
                "position"
            ],
            "properties": {
                "entry_date": {
                    "type": "string",
                    "example": "2024-01-15T08:00:00Z"
                },
                "name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "office_location": {
                    "type": "string",
                    "example": "Cabang Utama Jakarta"
                },
                "position": {
                    "type": "string",
                    "example": "Sales Executive"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "entry_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "office_location": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.PerformanceResponse": {
            "type": "object",
            "properties": {
                "employee": {
                    "description": "Object Employee utuh",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeResponse"
                        }
                    ]
                },
                "month": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.TargetPerformanceDetail"
                    }
                },
                "total_achievement": {
                    "type": "integer"
                },
                "total_target": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductRequest": {
            "type": "object",
            "required": [
                "category_id",
                "name"
            ],
            "properties": {
                "category_id": {
                    "type": "string",
                    "example": "uuid"
                },
                "name": {
                    "type": "string",
                    "example": "KUR Bank"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_norm": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductWithCategoryResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryResponse"
                },
                "category_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_norm": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.RecordAchievementRequest": {
            "type": "object",
            "required": [
                "nominal",
                "target_id"
            ],
            "properties": {
                "closing_date": {
                    "type": "string",
                    "example": "2026-05-10T14:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Pencairan KUR Nasabah A"
                },
                "nominal": {
                    "type": "integer",
                    "example": 150000000
                },
                "target_id": {
                    "type": "string",
                    "example": "uuid-target"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.TargetDetailResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employee_id": {
                    "description": "Tambahkan omitempty agar hilang jika tidak diperlukan",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "month": {
                    "type": "integer"
                },
                "nominal": {
                    "type": "integer"
                },
                "product": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductResponse"
                },
                "product_id": {
                    "description": "Tambahkan omitempty",
                    "type": "string"
                },
                "total_achievement": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.TargetPerformanceDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nominal": {
                    "type": "integer"
                },
                "product": {
                    "description": "Relasi produk langsung di sini",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductResponse"
                        }
                    ]
                },
                "total_achievement": {
                    "type": "integer"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.UpdateTargetNominalRequest": {
            "type": "object",
            "required": [
                "nominal"
            ],
            "properties": {
                "nominal": {
                    "type": "integer",
                    "example": 600000000
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.EmptyObj": {
            "type": "object"
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string",
                    "example": "pesan error"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_AchievementResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.AchievementResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_CategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_EmployeeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-array_github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductWithCategoryResponse"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_AchievementResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.AchievementResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_CategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.CategoryResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_EmployeeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.EmployeeResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_PerformanceResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.PerformanceResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_ProductWithCategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.ProductWithCategoryResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_delivery_http_dto_TargetDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_delivery_http_dto.TargetDetailResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faridlan_employee-tracker-api_internal_utils.SuccessResponse-github_com_faridlan_employee-tracker-api_internal_utils_EmptyObj": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_faridlan_employee-tracker-api_internal_utils.EmptyObj"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Employee Tracker API",
	Description:      "Ini adalah dokumentasi API untuk sistem pencatatan target dan performa Karyawan (Employee Tracker).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
